version: "1"
pipelines:
  - name: pharmacy-backend-deploy
    services:
      - name: pharmacy-api
        dockerfile: backend/Dockerfile
        port: 5050
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          PORT: 5050
        health-check:
          endpoint: /health
          interval: 30
          timeout: 10
  
  - name: pharmacy-frontend-deploy
    services:
      - name: pharmacy-ui
        dockerfile: frontend/Dockerfile
        port: 5173
        static: true
